ci: introduce Rust workflow
dashevo/rust-dpp pull request #5
Opened 2022-03-22 09:07 UTC by qrayven

add GitHub workflows

2022-04-05 09:33 UTC, shumkov requested changes

2022-04-05 09:33 UTC, shumkov commented on .github/workflows/rust.yml
> +          access_token: ${{ github.token }}
Can be handled with built-in workflow functionality https://docs.github.com/en/actions/using-jobs/using-concurrency

2022-04-05 09:33 UTC, shumkov commented on .github/workflows/rust.yml
> +  wasm-build:
I would rename it to `wasm-errors` for naming consistency.

2022-04-05 09:33 UTC, shumkov commented on .github/workflows/rust.yml
> +  errors:
I would rename it `rust-errors` for naming consistency

2022-04-05 09:33 UTC, shumkov commented on .github/workflows/rust.yml
> +name: rs-dpp
This is a workflow name option, which represents specific workflow not the entire repo. So I would keep the same name as you called the file: `Rust`.

2022-04-05 09:34 UTC, shumkov commented
Should we move other changes unrelated to CI to a separate PR?

2022-04-22 08:23 UTC, qrayven commented
> Should we move other changes unrelated to CI to a separate PR?

It was intended. But the pipeline wouldn't pass if those changes are not included. Or maybe you mean making the PR fixing pipeline first and then another PR with the pipeline in itself?

2022-04-25 14:55 UTC, shumkov commented
Yeah... I guess right now is not important to keep PR with specific atomic changes, but eventually, it would be nice to follow this practice.

2022-05-17 05:46 UTC, shumkov approved these changes
LGTM! 👍

2022-05-17 08:35 UTC, merged